package br.com.registrovet.RegistroVet.model.enums;

public enum Breeds {
    VIRA_LATA, CARAMELO, SHIH_TZU, PUG, PASTOR_ALEMÃO, POODLE, YORKSHIRE, HUSKY_SIBERIANO, PINSCHER,
    PERSA, SIAMÊS, RAGDOLL, SPHYNX,
    CALOPSITA, PERIQUITO, PAPAGAIO, ARARA, TUCANO, CANÁRIO,
    BETTA, DOURADO, CARPA, TETRA, PAULISTINHA, PALHAÇO,
    TARTARUGA, IGUANA, CAMALEÃO, COBRA, LAGARTO
}